on:
  workflow_dispatch:
  push:
    branches: [master]

name: "Update Transifex on Push"

jobs:
  push-translations-to-transifex:
    name: push-translations-to-transifex

    runs-on: ubuntu-latest
    permissions:
      actions: read

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: 📥 Push source file using transifex client
        uses: transifex/cli-action@584fd205cbe598773b5a81ce711fa44842678189 # v2
        with:
          token: ${{ secrets.TRANSIFEX_TOKEN }}
